import { CANVAS_WIDTH, TOP_BAR_HEIGHT, CELL_WIDTH, CELL_HEIGHT, PLANT_DATA, ENEMY_DATA } from './config.js';
import { GameState } from './state.js';
import { UI } from './ui.js';

export class Entity {
  constructor(col, row, type) { this.col=col; this.row=row; this.type=type; this.x=col*CELL_WIDTH; this.y=TOP_BAR_HEIGHT+row*CELL_HEIGHT; this.width=CELL_WIDTH*.7; this.height=CELL_HEIGHT*.8; this.drawX=this.x+(CELL_WIDTH-this.width)/2; this.drawY=this.y+(CELL_HEIGHT-this.height)/2+10; this.markedForDeletion=false; this.isEnemy=false; }
  update() {}
  draw() {}
}

export class Plant extends Entity {
  constructor(col,row,type) { super(col,row,type); const def=PLANT_DATA[type]; this.hp=def.hp; this.maxHp=def.hp; this.isPlatform=!!def.isPlatform; this.isLantern=!!def.isLantern; this.shootsDouble=!!def.shootsDouble; this.timer=0; this.secondaryShotTimer=0; this.hitFlash=0; }
  update(deltaTime) {
    if(this.hitFlash>0)this.hitFlash-=deltaTime;
    this.timer+=deltaTime;
    if(this.secondaryShotTimer>0){
      this.secondaryShotTimer-=deltaTime;
      if(this.secondaryShotTimer<=0 && !this.markedForDeletion){
        this.secondaryShotTimer=0;
        this.shoot();
      }
    }
    const def=PLANT_DATA[this.type];
    if(def.cooldown>0 && def.range>0){ const maxRange=def.range===Infinity?CANVAS_WIDTH:def.range*CELL_WIDTH; const enemyInRange=GameState.entities.some(e=>e.isEnemy&&e.row===this.row&&e.x>this.x&&e.x<=this.x+maxRange&&!e.markedForDeletion); if(this.timer>=def.cooldown){ if(enemyInRange){this.timer=0;this.shoot(); if(this.shootsDouble)this.secondaryShotTimer=180;}else this.timer=def.cooldown; }}
    else if(this.type==='sunflower'&&this.timer>=def.cooldown){this.timer=0;this.generateResource();}
  }
  takeDamage(amount){this.hp-=amount;this.hitFlash=120;if(this.hp<=0){this.hp=0;this.markedForDeletion=true;const cell=GameState.grid[this.col][this.row];if(this.isPlatform)cell.platform=null;else cell.entity=null;}}
  shoot(){const color=this.type==='puffshroom'?'#ce93d8':'#81c784';GameState.entities.push(new Projectile(this.drawX+this.width,this.drawY+this.height*.3,this.row,color));}
  generateResource(){GameState.entities.push(new ResourceDrop(this.drawX+Math.random()*this.width*.5,this.drawY+20,false));}
  draw(ctx){ctx.save();if(this.hitFlash>0)ctx.filter='brightness(2.5)';if(this.isPlatform){ctx.fillStyle=PLANT_DATA[this.type].color;ctx.beginPath();ctx.ellipse(this.drawX+this.width/2,this.drawY+this.height,this.width/1.4,this.height/3,0,0,Math.PI*2);ctx.fill();}else{ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(this.drawX+this.width/2,this.drawY+this.height-4,this.width/2,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=PLANT_DATA[this.type].color;if(this.type==='puffshroom'){ctx.fillRect(this.drawX+15,this.drawY+20,this.width-30,this.height-20);ctx.beginPath();ctx.arc(this.drawX+this.width/2,this.drawY+20,this.width/2+4,Math.PI,0);ctx.fill();}else if(this.isLantern){ctx.fillRect(this.drawX+10,this.drawY+10,this.width-20,this.height-10);ctx.fillStyle='#ffeb3b';ctx.beginPath();ctx.arc(this.drawX+this.width/2,this.drawY+this.height/2,10,0,Math.PI*2);ctx.fill();}else ctx.fillRect(this.drawX,this.drawY,this.width,this.height);if(!this.isLantern){ctx.fillStyle='white';ctx.beginPath();ctx.arc(this.drawX+this.width*.7,this.drawY+this.height*.3,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='black';ctx.beginPath();ctx.arc(this.drawX+this.width*.73,this.drawY+this.height*.3,2,0,Math.PI*2);ctx.fill();}}if(this.hp<this.maxHp){ctx.fillStyle='#c62828';ctx.fillRect(this.drawX,this.drawY-10,this.width,5);ctx.fillStyle='#76ff03';ctx.fillRect(this.drawX,this.drawY-10,this.width*(this.hp/this.maxHp),5);}ctx.restore();}
}

export class Enemy {
  constructor(row,type){this.row=row;this.type=type;this.isEnemy=true;const def=ENEMY_DATA[type];this.hp=def.hp;this.maxHp=def.hp;this.speed=def.speed;this.dps=def.damage;this.hiddenInFog=!!def.hiddenInFog;this.width=CELL_WIDTH*.6;this.height=CELL_HEIGHT*.7;this.x=CANVAS_WIDTH;this.y=TOP_BAR_HEIGHT+row*CELL_HEIGHT;this.drawX=this.x;this.drawY=this.y+(CELL_HEIGHT-this.height)/2+10;this.markedForDeletion=false;this.isEating=false;this.targetPlant=null;this.hitFlash=0;}
  update(deltaTime){if(this.hitFlash>0)this.hitFlash-=deltaTime;if(this.targetPlant?.markedForDeletion){this.isEating=false;this.targetPlant=null;}let hitPlant=false,potentialTarget=null;for(const ent of GameState.entities){if(ent instanceof Plant&&ent.row===this.row&&!ent.markedForDeletion&&this.drawX<=ent.drawX+ent.width&&this.drawX+this.width>=ent.drawX){hitPlant=true;if(!potentialTarget||(!potentialTarget.isPlatform&&ent.isPlatform===false))potentialTarget=ent;}}if(hitPlant&&potentialTarget){this.isEating=true;this.targetPlant=potentialTarget;potentialTarget.takeDamage(this.dps*deltaTime/1000);}else{this.isEating=false;this.x-=this.speed*deltaTime/1000;this.drawX=this.x;}if(this.drawX+this.width<0){GameState.gameOver=true;UI.showEndScreen(false,GameState.callbacks);}}
  takeDamage(amount){this.hp-=amount;this.hitFlash=120;ParticleSystem.spawnHitSpark(this.drawX+this.width/2,this.drawY+this.height/2);if(this.hp<=0){this.hp=0;this.markedForDeletion=true;ParticleSystem.spawnExplosion(this.drawX+this.width/2,this.drawY+this.height/2,ENEMY_DATA[this.type].color);}}
  draw(ctx){if(this.isHidden())return;ctx.save();if(this.hitFlash>0)ctx.filter='brightness(2.5)';ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(this.drawX+this.width/2,this.drawY+this.height-4,this.width/2,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=ENEMY_DATA[this.type].color;const bounce=this.isEating?0:Math.abs(Math.sin(Date.now()/150)*4);const waterOffset=GameState.currentMapDef.terrain[this.row]==='water'?14:0;ctx.beginPath();ctx.roundRect(this.drawX,this.drawY-bounce+waterOffset/2,this.width,this.height-waterOffset,8);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(this.drawX+this.width*.25,this.drawY-bounce+this.height*.25,4,0,Math.PI*2);ctx.arc(this.drawX+this.width*.5,this.drawY-bounce+this.height*.25,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#000';ctx.beginPath();ctx.arc(this.drawX+this.width*.22,this.drawY-bounce+this.height*.25,2,0,Math.PI*2);ctx.arc(this.drawX+this.width*.47,this.drawY-bounce+this.height*.25,2,0,Math.PI*2);ctx.fill();if(this.hp<this.maxHp){ctx.fillStyle='#c62828';ctx.fillRect(this.drawX,this.drawY-bounce-10,this.width,5);ctx.fillStyle='#76ff03';ctx.fillRect(this.drawX,this.drawY-bounce-10,this.width*(this.hp/this.maxHp),5);}ctx.restore();}
  isHidden(){const v=GameState.currentMapDef.visibility;if(!v?.enabled||!this.hiddenInFog)return false;const fogX=v.xStart*CELL_WIDTH+Math.sin(GameState.fogOffsetTimer)*40;if(this.drawX<=fogX)return false;return !GameState.entities.some(e=>e instanceof Plant&&e.isLantern&&e.row===this.row&&Math.abs(e.x-this.drawX)<CELL_WIDTH*2.5&&!e.markedForDeletion);}
}

export class Projectile { constructor(x,y,row,color){this.x=x;this.y=y;this.row=row;this.color=color;this.radius=7;this.speed=380;this.damage=25;this.markedForDeletion=false;} update(deltaTime){this.x+=this.speed*deltaTime/1000;for(const ent of GameState.entities){if(ent.isEnemy&&ent.row===this.row&&!ent.markedForDeletion&&!ent.isHidden()&&this.x>=ent.drawX&&this.x<=ent.drawX+ent.width){ent.takeDamage(this.damage);this.markedForDeletion=true;break;}}if(this.x>CANVAS_WIDTH+this.radius)this.markedForDeletion=true;} draw(ctx){ctx.fillStyle=this.color;ctx.beginPath();ctx.arc(this.x,this.y,this.radius,0,Math.PI*2);ctx.fill();} }
export class ResourceDrop { constructor(x,y,isSkyDrop){this.x=x;this.y=isSkyDrop?-40:y;this.targetY=isSkyDrop?TOP_BAR_HEIGHT+Math.floor(Math.random()*5)*CELL_HEIGHT+35:y+35;this.value=25;this.radius=16;this.markedForDeletion=false;this.lifeTime=10000;this.age=0;} update(deltaTime){this.age+=deltaTime;if(this.y<this.targetY)this.y+=55*deltaTime/1000;if(this.age>this.lifeTime)this.markedForDeletion=true;} draw(ctx){if(this.age>this.lifeTime-2000&&Math.floor(this.age/200)%2===0)return;ctx.fillStyle='#ffd700';ctx.beginPath();ctx.arc(this.x,this.y,this.radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff59d';ctx.beginPath();ctx.arc(this.x,this.y,this.radius*.6,0,Math.PI*2);ctx.fill();} collect(){GameState.resources+=this.value;UI.updateResources();GameState.floatingTexts.push(new FloatingText(this.x,this.y,`+${this.value}`,'#ffd700'));this.markedForDeletion=true;} }
export class Particle { constructor(x,y,color,vx,vy,size,life){this.x=x;this.y=y;this.color=color;this.vx=vx;this.vy=vy;this.size=size;this.life=life;this.maxLife=life;this.markedForDeletion=false;} update(deltaTime){this.x+=this.vx*deltaTime/1000;this.y+=this.vy*deltaTime/1000;this.life-=deltaTime;if(this.life<=0)this.markedForDeletion=true;} draw(ctx){ctx.save();ctx.globalAlpha=Math.max(0,this.life/this.maxLife);ctx.fillStyle=this.color;ctx.beginPath();ctx.arc(this.x,this.y,this.size,0,Math.PI*2);ctx.fill();ctx.restore();} }
export class FloatingText { constructor(x,y,text,color){this.x=x;this.y=y;this.text=text;this.color=color;this.life=1000;this.maxLife=1000;this.markedForDeletion=false;} update(deltaTime){this.y-=30*deltaTime/1000;this.life-=deltaTime;if(this.life<=0)this.markedForDeletion=true;} draw(ctx){ctx.save();ctx.globalAlpha=Math.max(0,this.life/this.maxLife);ctx.fillStyle=this.color;ctx.font='900 16px Nunito';ctx.shadowColor='black';ctx.shadowBlur=4;ctx.fillText(this.text,this.x,this.y);ctx.restore();} }
export const ParticleSystem={spawnExplosion(x,y,color){for(let i=0;i<10;i++){const angle=Math.random()*Math.PI*2,speed=40+Math.random()*80;GameState.particles.push(new Particle(x,y,color,Math.cos(angle)*speed,Math.sin(angle)*speed,3+Math.random()*3,600));}},spawnHitSpark(x,y){for(let i=0;i<4;i++){const angle=Math.random()*Math.PI*2,speed=20+Math.random()*40;GameState.particles.push(new Particle(x,y,'#fff',Math.cos(angle)*speed,Math.sin(angle)*speed,2,300));}}};
